import {Post} from "./interfaces/interfaces";

export let POSTS: Post[] = [
  {id: 7, title:'First post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
  {id: 6, title:'Second post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
  {id: 5, title:'Thr post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
  {id: 4, title:'Fours post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
  {id: 3, title:'Fiw post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
  {id: 2, title:'S post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
  {id: 1, title:'S post',urlPict: '', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto, blanditiis cupiditate et maxime numquam odio voluptas! Accusantium amet autem consequuntur, dicta, doloribus dolorum eos et facere fuga, id mollitia nisi sequi suscipit! Dolorem ducimus eveniet excepturi nobis suscipit. Delectus dolorum expedita magni. Architecto doloremque laudantium nam quae quaerat quod?',author: 'S.Y.Moskalenko',date:new Date},
]
